import json
from pathlib import Path
from urllib import request

ROOT = Path(__file__).parent

KEYWORDS = {
    'False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield'
}

def main():
    all_elements_response = request.urlopen("https://raw.githubusercontent.com/jozo/all-html-elements-and-attributes/refs/heads/master/html-elements.json")
    all_elements = json.loads(all_elements_response.read())

    elements = []

    for name, data in all_elements.items():
        if "*" in name:
            continue
        if name in KEYWORDS:
            name = f"{name}_"
        attributes = [attribute.replace("-", "_") for attribute in data.get("attributes", [])]
        for i, attribute in enumerate(attributes):
            if attribute in KEYWORDS:
                attributes[i] = f"{attribute}_"
        args = ",\n".join(
            [
                f'        {attribute}: str | None = None'
                for attribute in attributes
            ]
        )
        super_args = ",\n".join(
            [
                f'            {attribute}={attribute}'
                for attribute in attributes
            ]
        )
        code = f"""class {name}(Element):
    name = "{name}"
    def __init__(
        self,
        styles: css | None = None,
{args}{',\n' if len(attributes) > 0 else ''}        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
{super_args}{',\n' if len(attributes) > 0 else ''}            **attr,
        )
"""

        elements.append(code)

    with open(ROOT / "html.py", "w") as f:
        f.write(f"""# -------------------------------------
# AUTOGENERATED FILE - DO NOT EDIT
# -------------------------------------

from html_dsl.element import Element, css

{'\n\n'.join(elements)}
""")



if __name__ == "__main__":
    main()
