# -------------------------------------
# AUTOGENERATED FILE - DO NOT EDIT
# -------------------------------------

from html_dsl.element import Element, css

class a(Element):
    name = "a"
    def __init__(
        self,
        styles: css | None = None,
        attributionsrc: str | None = None,
        download: str | None = None,
        href: str | None = None,
        hreflang: str | None = None,
        ping: str | None = None,
        referrerpolicy: str | None = None,
        rel: str | None = None,
        target: str | None = None,
        type: str | None = None,
        charset: str | None = None,
        coords: str | None = None,
        name: str | None = None,
        rev: str | None = None,
        shape: str | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            attributionsrc=attributionsrc,
            download=download,
            href=href,
            hreflang=hreflang,
            ping=ping,
            referrerpolicy=referrerpolicy,
            rel=rel,
            target=target,
            type=type,
            charset=charset,
            coords=coords,
            name=name,
            rev=rev,
            shape=shape,
            **attr,
        )


class abbr(Element):
    name = "abbr"
    def __init__(
        self,
        styles: css | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            **attr,
        )


class acronym(Element):
    name = "acronym"
    def __init__(
        self,
        styles: css | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            **attr,
        )


class address(Element):
    name = "address"
    def __init__(
        self,
        styles: css | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            **attr,
        )


class area(Element):
    name = "area"
    def __init__(
        self,
        styles: css | None = None,
        alt: str | None = None,
        coords: str | None = None,
        download: str | None = None,
        href: str | None = None,
        ping: str | None = None,
        referrerpolicy: str | None = None,
        rel: str | None = None,
        shape: str | None = None,
        target: str | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            alt=alt,
            coords=coords,
            download=download,
            href=href,
            ping=ping,
            referrerpolicy=referrerpolicy,
            rel=rel,
            shape=shape,
            target=target,
            **attr,
        )


class article(Element):
    name = "article"
    def __init__(
        self,
        styles: css | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            **attr,
        )


class aside(Element):
    name = "aside"
    def __init__(
        self,
        styles: css | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            **attr,
        )


class audio(Element):
    name = "audio"
    def __init__(
        self,
        styles: css | None = None,
        autoplay: str | None = None,
        controls: str | None = None,
        controlslist: str | None = None,
        crossorigin: str | None = None,
        disableremoteplayback: str | None = None,
        loop: str | None = None,
        muted: str | None = None,
        preload: str | None = None,
        src: str | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            autoplay=autoplay,
            controls=controls,
            controlslist=controlslist,
            crossorigin=crossorigin,
            disableremoteplayback=disableremoteplayback,
            loop=loop,
            muted=muted,
            preload=preload,
            src=src,
            **attr,
        )


class b(Element):
    name = "b"
    def __init__(
        self,
        styles: css | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            **attr,
        )


class base(Element):
    name = "base"
    def __init__(
        self,
        styles: css | None = None,
        href: str | None = None,
        target: str | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            href=href,
            target=target,
            **attr,
        )


class bdi(Element):
    name = "bdi"
    def __init__(
        self,
        styles: css | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            **attr,
        )


class bdo(Element):
    name = "bdo"
    def __init__(
        self,
        styles: css | None = None,
        dir: str | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            dir=dir,
            **attr,
        )


class big(Element):
    name = "big"
    def __init__(
        self,
        styles: css | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            **attr,
        )


class blockquote(Element):
    name = "blockquote"
    def __init__(
        self,
        styles: css | None = None,
        cite: str | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            cite=cite,
            **attr,
        )


class body(Element):
    name = "body"
    def __init__(
        self,
        styles: css | None = None,
        alink: str | None = None,
        background: str | None = None,
        bgcolor: str | None = None,
        bottommargin: str | None = None,
        leftmargin: str | None = None,
        link: str | None = None,
        onafterprint: str | None = None,
        onbeforeprint: str | None = None,
        onbeforeunload: str | None = None,
        onblur: str | None = None,
        onerror: str | None = None,
        onfocus: str | None = None,
        onhashchange: str | None = None,
        onlanguagechange: str | None = None,
        onload: str | None = None,
        onmessage: str | None = None,
        onoffline: str | None = None,
        ononline: str | None = None,
        onpopstate: str | None = None,
        onresize: str | None = None,
        onstorage: str | None = None,
        onunload: str | None = None,
        rightmargin: str | None = None,
        text: str | None = None,
        topmargin: str | None = None,
        vlink: str | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            alink=alink,
            background=background,
            bgcolor=bgcolor,
            bottommargin=bottommargin,
            leftmargin=leftmargin,
            link=link,
            onafterprint=onafterprint,
            onbeforeprint=onbeforeprint,
            onbeforeunload=onbeforeunload,
            onblur=onblur,
            onerror=onerror,
            onfocus=onfocus,
            onhashchange=onhashchange,
            onlanguagechange=onlanguagechange,
            onload=onload,
            onmessage=onmessage,
            onoffline=onoffline,
            ononline=ononline,
            onpopstate=onpopstate,
            onresize=onresize,
            onstorage=onstorage,
            onunload=onunload,
            rightmargin=rightmargin,
            text=text,
            topmargin=topmargin,
            vlink=vlink,
            **attr,
        )


class br(Element):
    name = "br"
    def __init__(
        self,
        styles: css | None = None,
        clear: str | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            clear=clear,
            **attr,
        )


class button(Element):
    name = "button"
    def __init__(
        self,
        styles: css | None = None,
        autofocus: str | None = None,
        disabled: str | None = None,
        form: str | None = None,
        formaction: str | None = None,
        formenctype: str | None = None,
        formmethod: str | None = None,
        formnovalidate: str | None = None,
        formtarget: str | None = None,
        name: str | None = None,
        popovertarget: str | None = None,
        popovertargetaction: str | None = None,
        type: str | None = None,
        value: str | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            autofocus=autofocus,
            disabled=disabled,
            form=form,
            formaction=formaction,
            formenctype=formenctype,
            formmethod=formmethod,
            formnovalidate=formnovalidate,
            formtarget=formtarget,
            name=name,
            popovertarget=popovertarget,
            popovertargetaction=popovertargetaction,
            type=type,
            value=value,
            **attr,
        )


class canvas(Element):
    name = "canvas"
    def __init__(
        self,
        styles: css | None = None,
        height: str | None = None,
        moz_opaque: str | None = None,
        width: str | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            height=height,
            moz_opaque=moz_opaque,
            width=width,
            **attr,
        )


class caption(Element):
    name = "caption"
    def __init__(
        self,
        styles: css | None = None,
        align: str | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            align=align,
            **attr,
        )


class center(Element):
    name = "center"
    def __init__(
        self,
        styles: css | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            **attr,
        )


class cite(Element):
    name = "cite"
    def __init__(
        self,
        styles: css | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            **attr,
        )


class code(Element):
    name = "code"
    def __init__(
        self,
        styles: css | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            **attr,
        )


class col(Element):
    name = "col"
    def __init__(
        self,
        styles: css | None = None,
        span: str | None = None,
        align: str | None = None,
        bgcolor: str | None = None,
        char: str | None = None,
        charoff: str | None = None,
        valign: str | None = None,
        width: str | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            span=span,
            align=align,
            bgcolor=bgcolor,
            char=char,
            charoff=charoff,
            valign=valign,
            width=width,
            **attr,
        )


class colgroup(Element):
    name = "colgroup"
    def __init__(
        self,
        styles: css | None = None,
        span: str | None = None,
        align: str | None = None,
        bgcolor: str | None = None,
        char: str | None = None,
        charoff: str | None = None,
        valign: str | None = None,
        width: str | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            span=span,
            align=align,
            bgcolor=bgcolor,
            char=char,
            charoff=charoff,
            valign=valign,
            width=width,
            **attr,
        )


class data(Element):
    name = "data"
    def __init__(
        self,
        styles: css | None = None,
        value: str | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            value=value,
            **attr,
        )


class datalist(Element):
    name = "datalist"
    def __init__(
        self,
        styles: css | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            **attr,
        )


class dd(Element):
    name = "dd"
    def __init__(
        self,
        styles: css | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            **attr,
        )


class del_(Element):
    name = "del_"
    def __init__(
        self,
        styles: css | None = None,
        cite: str | None = None,
        datetime: str | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            cite=cite,
            datetime=datetime,
            **attr,
        )


class details(Element):
    name = "details"
    def __init__(
        self,
        styles: css | None = None,
        open: str | None = None,
        name: str | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            open=open,
            name=name,
            **attr,
        )


class dfn(Element):
    name = "dfn"
    def __init__(
        self,
        styles: css | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            **attr,
        )


class dialog(Element):
    name = "dialog"
    def __init__(
        self,
        styles: css | None = None,
        open: str | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            open=open,
            **attr,
        )


class dir(Element):
    name = "dir"
    def __init__(
        self,
        styles: css | None = None,
        compact: str | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            compact=compact,
            **attr,
        )


class div(Element):
    name = "div"
    def __init__(
        self,
        styles: css | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            **attr,
        )


class dl(Element):
    name = "dl"
    def __init__(
        self,
        styles: css | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            **attr,
        )


class dt(Element):
    name = "dt"
    def __init__(
        self,
        styles: css | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            **attr,
        )


class em(Element):
    name = "em"
    def __init__(
        self,
        styles: css | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            **attr,
        )


class embed(Element):
    name = "embed"
    def __init__(
        self,
        styles: css | None = None,
        height: str | None = None,
        src: str | None = None,
        type: str | None = None,
        width: str | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            height=height,
            src=src,
            type=type,
            width=width,
            **attr,
        )


class fencedframe(Element):
    name = "fencedframe"
    def __init__(
        self,
        styles: css | None = None,
        allow: str | None = None,
        height: str | None = None,
        width: str | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            allow=allow,
            height=height,
            width=width,
            **attr,
        )


class fieldset(Element):
    name = "fieldset"
    def __init__(
        self,
        styles: css | None = None,
        disabled: str | None = None,
        form: str | None = None,
        name: str | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            disabled=disabled,
            form=form,
            name=name,
            **attr,
        )


class figcaption(Element):
    name = "figcaption"
    def __init__(
        self,
        styles: css | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            **attr,
        )


class figure(Element):
    name = "figure"
    def __init__(
        self,
        styles: css | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            **attr,
        )


class font(Element):
    name = "font"
    def __init__(
        self,
        styles: css | None = None,
        color: str | None = None,
        face: str | None = None,
        size: str | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            color=color,
            face=face,
            size=size,
            **attr,
        )


class footer(Element):
    name = "footer"
    def __init__(
        self,
        styles: css | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            **attr,
        )


class form(Element):
    name = "form"
    def __init__(
        self,
        styles: css | None = None,
        accept: str | None = None,
        accept_charset: str | None = None,
        autocapitalize: str | None = None,
        autocomplete: str | None = None,
        name: str | None = None,
        rel: str | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            accept=accept,
            accept_charset=accept_charset,
            autocapitalize=autocapitalize,
            autocomplete=autocomplete,
            name=name,
            rel=rel,
            **attr,
        )


class frame(Element):
    name = "frame"
    def __init__(
        self,
        styles: css | None = None,
        src: str | None = None,
        name: str | None = None,
        noresize: str | None = None,
        scrolling: str | None = None,
        marginheight: str | None = None,
        marginwidth: str | None = None,
        frameborder: str | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            src=src,
            name=name,
            noresize=noresize,
            scrolling=scrolling,
            marginheight=marginheight,
            marginwidth=marginwidth,
            frameborder=frameborder,
            **attr,
        )


class frameset(Element):
    name = "frameset"
    def __init__(
        self,
        styles: css | None = None,
        cols: str | None = None,
        rows: str | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            cols=cols,
            rows=rows,
            **attr,
        )


class h1(Element):
    name = "h1"
    def __init__(
        self,
        styles: css | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            **attr,
        )


class h2(Element):
    name = "h2"
    def __init__(
        self,
        styles: css | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            **attr,
        )


class h3(Element):
    name = "h3"
    def __init__(
        self,
        styles: css | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            **attr,
        )


class h4(Element):
    name = "h4"
    def __init__(
        self,
        styles: css | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            **attr,
        )


class h5(Element):
    name = "h5"
    def __init__(
        self,
        styles: css | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            **attr,
        )


class h6(Element):
    name = "h6"
    def __init__(
        self,
        styles: css | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            **attr,
        )


class head(Element):
    name = "head"
    def __init__(
        self,
        styles: css | None = None,
        profile: str | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            profile=profile,
            **attr,
        )


class header(Element):
    name = "header"
    def __init__(
        self,
        styles: css | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            **attr,
        )


class hgroup(Element):
    name = "hgroup"
    def __init__(
        self,
        styles: css | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            **attr,
        )


class hr(Element):
    name = "hr"
    def __init__(
        self,
        styles: css | None = None,
        align: str | None = None,
        color: str | None = None,
        noshade: str | None = None,
        size: str | None = None,
        width: str | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            align=align,
            color=color,
            noshade=noshade,
            size=size,
            width=width,
            **attr,
        )


class html(Element):
    name = "html"
    def __init__(
        self,
        styles: css | None = None,
        version: str | None = None,
        xmlns: str | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            version=version,
            xmlns=xmlns,
            **attr,
        )


class i(Element):
    name = "i"
    def __init__(
        self,
        styles: css | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            **attr,
        )


class iframe(Element):
    name = "iframe"
    def __init__(
        self,
        styles: css | None = None,
        allow: str | None = None,
        allowfullscreen: str | None = None,
        allowpaymentrequest: str | None = None,
        browsingtopics: str | None = None,
        credentialless: str | None = None,
        csp: str | None = None,
        height: str | None = None,
        loading: str | None = None,
        name: str | None = None,
        referrerpolicy: str | None = None,
        sandbox: str | None = None,
        src: str | None = None,
        srcdoc: str | None = None,
        width: str | None = None,
        align: str | None = None,
        frameborder: str | None = None,
        longdesc: str | None = None,
        marginheight: str | None = None,
        marginwidth: str | None = None,
        scrolling: str | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            allow=allow,
            allowfullscreen=allowfullscreen,
            allowpaymentrequest=allowpaymentrequest,
            browsingtopics=browsingtopics,
            credentialless=credentialless,
            csp=csp,
            height=height,
            loading=loading,
            name=name,
            referrerpolicy=referrerpolicy,
            sandbox=sandbox,
            src=src,
            srcdoc=srcdoc,
            width=width,
            align=align,
            frameborder=frameborder,
            longdesc=longdesc,
            marginheight=marginheight,
            marginwidth=marginwidth,
            scrolling=scrolling,
            **attr,
        )


class img(Element):
    name = "img"
    def __init__(
        self,
        styles: css | None = None,
        alt: str | None = None,
        attributionsrc: str | None = None,
        crossorigin: str | None = None,
        decoding: str | None = None,
        elementtiming: str | None = None,
        fetchpriority: str | None = None,
        height: str | None = None,
        ismap: str | None = None,
        loading: str | None = None,
        referrerpolicy: str | None = None,
        sizes: str | None = None,
        src: str | None = None,
        srcset: str | None = None,
        width: str | None = None,
        usemap: str | None = None,
        align: str | None = None,
        border: str | None = None,
        hspace: str | None = None,
        longdesc: str | None = None,
        name: str | None = None,
        vspace: str | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            alt=alt,
            attributionsrc=attributionsrc,
            crossorigin=crossorigin,
            decoding=decoding,
            elementtiming=elementtiming,
            fetchpriority=fetchpriority,
            height=height,
            ismap=ismap,
            loading=loading,
            referrerpolicy=referrerpolicy,
            sizes=sizes,
            src=src,
            srcset=srcset,
            width=width,
            usemap=usemap,
            align=align,
            border=border,
            hspace=hspace,
            longdesc=longdesc,
            name=name,
            vspace=vspace,
            **attr,
        )


class input(Element):
    name = "input"
    def __init__(
        self,
        styles: css | None = None,
        accept: str | None = None,
        alt: str | None = None,
        autocapitalize: str | None = None,
        autocomplete: str | None = None,
        autofocus: str | None = None,
        capture: str | None = None,
        checked: str | None = None,
        dirname: str | None = None,
        disabled: str | None = None,
        form: str | None = None,
        formaction: str | None = None,
        formenctype: str | None = None,
        formmethod: str | None = None,
        formnovalidate: str | None = None,
        formtarget: str | None = None,
        height: str | None = None,
        id: str | None = None,
        inputmode: str | None = None,
        list: str | None = None,
        max: str | None = None,
        maxlength: str | None = None,
        min: str | None = None,
        minlength: str | None = None,
        multiple: str | None = None,
        name: str | None = None,
        pattern: str | None = None,
        placeholder: str | None = None,
        popovertarget: str | None = None,
        popovertargetaction: str | None = None,
        readonly: str | None = None,
        required: str | None = None,
        size: str | None = None,
        src: str | None = None,
        step: str | None = None,
        tabindex: str | None = None,
        title: str | None = None,
        type: str | None = None,
        value: str | None = None,
        width: str | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            accept=accept,
            alt=alt,
            autocapitalize=autocapitalize,
            autocomplete=autocomplete,
            autofocus=autofocus,
            capture=capture,
            checked=checked,
            dirname=dirname,
            disabled=disabled,
            form=form,
            formaction=formaction,
            formenctype=formenctype,
            formmethod=formmethod,
            formnovalidate=formnovalidate,
            formtarget=formtarget,
            height=height,
            id=id,
            inputmode=inputmode,
            list=list,
            max=max,
            maxlength=maxlength,
            min=min,
            minlength=minlength,
            multiple=multiple,
            name=name,
            pattern=pattern,
            placeholder=placeholder,
            popovertarget=popovertarget,
            popovertargetaction=popovertargetaction,
            readonly=readonly,
            required=required,
            size=size,
            src=src,
            step=step,
            tabindex=tabindex,
            title=title,
            type=type,
            value=value,
            width=width,
            **attr,
        )


class ins(Element):
    name = "ins"
    def __init__(
        self,
        styles: css | None = None,
        cite: str | None = None,
        datetime: str | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            cite=cite,
            datetime=datetime,
            **attr,
        )


class kbd(Element):
    name = "kbd"
    def __init__(
        self,
        styles: css | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            **attr,
        )


class label(Element):
    name = "label"
    def __init__(
        self,
        styles: css | None = None,
        for_: str | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            for_=for_,
            **attr,
        )


class legend(Element):
    name = "legend"
    def __init__(
        self,
        styles: css | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            **attr,
        )


class li(Element):
    name = "li"
    def __init__(
        self,
        styles: css | None = None,
        value: str | None = None,
        type: str | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            value=value,
            type=type,
            **attr,
        )


class link(Element):
    name = "link"
    def __init__(
        self,
        styles: css | None = None,
        as_: str | None = None,
        blocking: str | None = None,
        crossorigin: str | None = None,
        disabled: str | None = None,
        fetchpriority: str | None = None,
        href: str | None = None,
        hreflang: str | None = None,
        imagesizes: str | None = None,
        imagesrcset: str | None = None,
        integrity: str | None = None,
        media: str | None = None,
        referrerpolicy: str | None = None,
        rel: str | None = None,
        sizes: str | None = None,
        title: str | None = None,
        type: str | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            as_=as_,
            blocking=blocking,
            crossorigin=crossorigin,
            disabled=disabled,
            fetchpriority=fetchpriority,
            href=href,
            hreflang=hreflang,
            imagesizes=imagesizes,
            imagesrcset=imagesrcset,
            integrity=integrity,
            media=media,
            referrerpolicy=referrerpolicy,
            rel=rel,
            sizes=sizes,
            title=title,
            type=type,
            **attr,
        )


class main(Element):
    name = "main"
    def __init__(
        self,
        styles: css | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            **attr,
        )


class map(Element):
    name = "map"
    def __init__(
        self,
        styles: css | None = None,
        name: str | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            name=name,
            **attr,
        )


class mark(Element):
    name = "mark"
    def __init__(
        self,
        styles: css | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            **attr,
        )


class marquee(Element):
    name = "marquee"
    def __init__(
        self,
        styles: css | None = None,
        behavior: str | None = None,
        bgcolor: str | None = None,
        direction: str | None = None,
        height: str | None = None,
        hspace: str | None = None,
        loop: str | None = None,
        scrollamount: str | None = None,
        scrolldelay: str | None = None,
        truespeed: str | None = None,
        vspace: str | None = None,
        width: str | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            behavior=behavior,
            bgcolor=bgcolor,
            direction=direction,
            height=height,
            hspace=hspace,
            loop=loop,
            scrollamount=scrollamount,
            scrolldelay=scrolldelay,
            truespeed=truespeed,
            vspace=vspace,
            width=width,
            **attr,
        )


class menu(Element):
    name = "menu"
    def __init__(
        self,
        styles: css | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            **attr,
        )


class meta(Element):
    name = "meta"
    def __init__(
        self,
        styles: css | None = None,
        charset: str | None = None,
        content: str | None = None,
        http_equiv: str | None = None,
        name: str | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            charset=charset,
            content=content,
            http_equiv=http_equiv,
            name=name,
            **attr,
        )


class meter(Element):
    name = "meter"
    def __init__(
        self,
        styles: css | None = None,
        value: str | None = None,
        min: str | None = None,
        max: str | None = None,
        low: str | None = None,
        high: str | None = None,
        optimum: str | None = None,
        form: str | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            value=value,
            min=min,
            max=max,
            low=low,
            high=high,
            optimum=optimum,
            form=form,
            **attr,
        )


class nav(Element):
    name = "nav"
    def __init__(
        self,
        styles: css | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            **attr,
        )


class nobr(Element):
    name = "nobr"
    def __init__(
        self,
        styles: css | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            **attr,
        )


class noembed(Element):
    name = "noembed"
    def __init__(
        self,
        styles: css | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            **attr,
        )


class noframes(Element):
    name = "noframes"
    def __init__(
        self,
        styles: css | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            **attr,
        )


class noscript(Element):
    name = "noscript"
    def __init__(
        self,
        styles: css | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            **attr,
        )


class object(Element):
    name = "object"
    def __init__(
        self,
        styles: css | None = None,
        archive: str | None = None,
        border: str | None = None,
        classid: str | None = None,
        codebase: str | None = None,
        codetype: str | None = None,
        data: str | None = None,
        declare: str | None = None,
        form: str | None = None,
        height: str | None = None,
        name: str | None = None,
        standby: str | None = None,
        type: str | None = None,
        usemap: str | None = None,
        width: str | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            archive=archive,
            border=border,
            classid=classid,
            codebase=codebase,
            codetype=codetype,
            data=data,
            declare=declare,
            form=form,
            height=height,
            name=name,
            standby=standby,
            type=type,
            usemap=usemap,
            width=width,
            **attr,
        )


class ol(Element):
    name = "ol"
    def __init__(
        self,
        styles: css | None = None,
        reversed: str | None = None,
        start: str | None = None,
        type: str | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            reversed=reversed,
            start=start,
            type=type,
            **attr,
        )


class optgroup(Element):
    name = "optgroup"
    def __init__(
        self,
        styles: css | None = None,
        disabled: str | None = None,
        label: str | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            disabled=disabled,
            label=label,
            **attr,
        )


class option(Element):
    name = "option"
    def __init__(
        self,
        styles: css | None = None,
        disabled: str | None = None,
        label: str | None = None,
        selected: str | None = None,
        value: str | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            disabled=disabled,
            label=label,
            selected=selected,
            value=value,
            **attr,
        )


class output(Element):
    name = "output"
    def __init__(
        self,
        styles: css | None = None,
        for_: str | None = None,
        form: str | None = None,
        name: str | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            for_=for_,
            form=form,
            name=name,
            **attr,
        )


class p(Element):
    name = "p"
    def __init__(
        self,
        styles: css | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            **attr,
        )


class param(Element):
    name = "param"
    def __init__(
        self,
        styles: css | None = None,
        name: str | None = None,
        value: str | None = None,
        type: str | None = None,
        valuetype: str | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            name=name,
            value=value,
            type=type,
            valuetype=valuetype,
            **attr,
        )


class picture(Element):
    name = "picture"
    def __init__(
        self,
        styles: css | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            **attr,
        )


class plaintext(Element):
    name = "plaintext"
    def __init__(
        self,
        styles: css | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            **attr,
        )


class portal(Element):
    name = "portal"
    def __init__(
        self,
        styles: css | None = None,
        referrerpolicy: str | None = None,
        src: str | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            referrerpolicy=referrerpolicy,
            src=src,
            **attr,
        )


class pre(Element):
    name = "pre"
    def __init__(
        self,
        styles: css | None = None,
        width: str | None = None,
        wrap: str | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            width=width,
            wrap=wrap,
            **attr,
        )


class progress(Element):
    name = "progress"
    def __init__(
        self,
        styles: css | None = None,
        max: str | None = None,
        value: str | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            max=max,
            value=value,
            **attr,
        )


class q(Element):
    name = "q"
    def __init__(
        self,
        styles: css | None = None,
        cite: str | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            cite=cite,
            **attr,
        )


class rb(Element):
    name = "rb"
    def __init__(
        self,
        styles: css | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            **attr,
        )


class rp(Element):
    name = "rp"
    def __init__(
        self,
        styles: css | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            **attr,
        )


class rt(Element):
    name = "rt"
    def __init__(
        self,
        styles: css | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            **attr,
        )


class rtc(Element):
    name = "rtc"
    def __init__(
        self,
        styles: css | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            **attr,
        )


class ruby(Element):
    name = "ruby"
    def __init__(
        self,
        styles: css | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            **attr,
        )


class s(Element):
    name = "s"
    def __init__(
        self,
        styles: css | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            **attr,
        )


class samp(Element):
    name = "samp"
    def __init__(
        self,
        styles: css | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            **attr,
        )


class script(Element):
    name = "script"
    def __init__(
        self,
        styles: css | None = None,
        async_: str | None = None,
        attributionsrc: str | None = None,
        blocking: str | None = None,
        crossorigin: str | None = None,
        defer: str | None = None,
        fetchpriority: str | None = None,
        integrity: str | None = None,
        nomodule: str | None = None,
        nonce: str | None = None,
        referrerpolicy: str | None = None,
        src: str | None = None,
        type: str | None = None,
        charset: str | None = None,
        language: str | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            async_=async_,
            attributionsrc=attributionsrc,
            blocking=blocking,
            crossorigin=crossorigin,
            defer=defer,
            fetchpriority=fetchpriority,
            integrity=integrity,
            nomodule=nomodule,
            nonce=nonce,
            referrerpolicy=referrerpolicy,
            src=src,
            type=type,
            charset=charset,
            language=language,
            **attr,
        )


class search(Element):
    name = "search"
    def __init__(
        self,
        styles: css | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            **attr,
        )


class section(Element):
    name = "section"
    def __init__(
        self,
        styles: css | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            **attr,
        )


class select(Element):
    name = "select"
    def __init__(
        self,
        styles: css | None = None,
        autocomplete: str | None = None,
        autofocus: str | None = None,
        disabled: str | None = None,
        form: str | None = None,
        multiple: str | None = None,
        name: str | None = None,
        required: str | None = None,
        size: str | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            autocomplete=autocomplete,
            autofocus=autofocus,
            disabled=disabled,
            form=form,
            multiple=multiple,
            name=name,
            required=required,
            size=size,
            **attr,
        )


class slot(Element):
    name = "slot"
    def __init__(
        self,
        styles: css | None = None,
        name: str | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            name=name,
            **attr,
        )


class small(Element):
    name = "small"
    def __init__(
        self,
        styles: css | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            **attr,
        )


class source(Element):
    name = "source"
    def __init__(
        self,
        styles: css | None = None,
        type: str | None = None,
        src: str | None = None,
        srcset: str | None = None,
        sizes: str | None = None,
        media: str | None = None,
        height: str | None = None,
        width: str | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            type=type,
            src=src,
            srcset=srcset,
            sizes=sizes,
            media=media,
            height=height,
            width=width,
            **attr,
        )


class span(Element):
    name = "span"
    def __init__(
        self,
        styles: css | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            **attr,
        )


class strike(Element):
    name = "strike"
    def __init__(
        self,
        styles: css | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            **attr,
        )


class strong(Element):
    name = "strong"
    def __init__(
        self,
        styles: css | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            **attr,
        )


class style(Element):
    name = "style"
    def __init__(
        self,
        styles: css | None = None,
        blocking: str | None = None,
        media: str | None = None,
        nonce: str | None = None,
        title: str | None = None,
        type: str | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            blocking=blocking,
            media=media,
            nonce=nonce,
            title=title,
            type=type,
            **attr,
        )


class sub(Element):
    name = "sub"
    def __init__(
        self,
        styles: css | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            **attr,
        )


class summary(Element):
    name = "summary"
    def __init__(
        self,
        styles: css | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            **attr,
        )


class sup(Element):
    name = "sup"
    def __init__(
        self,
        styles: css | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            **attr,
        )


class table(Element):
    name = "table"
    def __init__(
        self,
        styles: css | None = None,
        align: str | None = None,
        bgcolor: str | None = None,
        border: str | None = None,
        cellpadding: str | None = None,
        cellspacing: str | None = None,
        frame: str | None = None,
        rules: str | None = None,
        summary: str | None = None,
        width: str | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            align=align,
            bgcolor=bgcolor,
            border=border,
            cellpadding=cellpadding,
            cellspacing=cellspacing,
            frame=frame,
            rules=rules,
            summary=summary,
            width=width,
            **attr,
        )


class tbody(Element):
    name = "tbody"
    def __init__(
        self,
        styles: css | None = None,
        align: str | None = None,
        bgcolor: str | None = None,
        char: str | None = None,
        charoff: str | None = None,
        valign: str | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            align=align,
            bgcolor=bgcolor,
            char=char,
            charoff=charoff,
            valign=valign,
            **attr,
        )


class td(Element):
    name = "td"
    def __init__(
        self,
        styles: css | None = None,
        colspan: str | None = None,
        headers: str | None = None,
        rowspan: str | None = None,
        abbr: str | None = None,
        align: str | None = None,
        axis: str | None = None,
        bgcolor: str | None = None,
        char: str | None = None,
        charoff: str | None = None,
        height: str | None = None,
        scope: str | None = None,
        valign: str | None = None,
        width: str | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            colspan=colspan,
            headers=headers,
            rowspan=rowspan,
            abbr=abbr,
            align=align,
            axis=axis,
            bgcolor=bgcolor,
            char=char,
            charoff=charoff,
            height=height,
            scope=scope,
            valign=valign,
            width=width,
            **attr,
        )


class template(Element):
    name = "template"
    def __init__(
        self,
        styles: css | None = None,
        shadowrootmode: str | None = None,
        shadowrootclonable: str | None = None,
        shadowrootdelegatesfocus: str | None = None,
        shadowrootserializable: str | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            shadowrootmode=shadowrootmode,
            shadowrootclonable=shadowrootclonable,
            shadowrootdelegatesfocus=shadowrootdelegatesfocus,
            shadowrootserializable=shadowrootserializable,
            **attr,
        )


class textarea(Element):
    name = "textarea"
    def __init__(
        self,
        styles: css | None = None,
        autocapitalize: str | None = None,
        autocomplete: str | None = None,
        autocorrect: str | None = None,
        autofocus: str | None = None,
        cols: str | None = None,
        dirname: str | None = None,
        disabled: str | None = None,
        form: str | None = None,
        maxlength: str | None = None,
        minlength: str | None = None,
        name: str | None = None,
        placeholder: str | None = None,
        readonly: str | None = None,
        required: str | None = None,
        rows: str | None = None,
        spellcheck: str | None = None,
        wrap: str | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            autocapitalize=autocapitalize,
            autocomplete=autocomplete,
            autocorrect=autocorrect,
            autofocus=autofocus,
            cols=cols,
            dirname=dirname,
            disabled=disabled,
            form=form,
            maxlength=maxlength,
            minlength=minlength,
            name=name,
            placeholder=placeholder,
            readonly=readonly,
            required=required,
            rows=rows,
            spellcheck=spellcheck,
            wrap=wrap,
            **attr,
        )


class tfoot(Element):
    name = "tfoot"
    def __init__(
        self,
        styles: css | None = None,
        align: str | None = None,
        bgcolor: str | None = None,
        char: str | None = None,
        charoff: str | None = None,
        valign: str | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            align=align,
            bgcolor=bgcolor,
            char=char,
            charoff=charoff,
            valign=valign,
            **attr,
        )


class th(Element):
    name = "th"
    def __init__(
        self,
        styles: css | None = None,
        abbr: str | None = None,
        colspan: str | None = None,
        headers: str | None = None,
        rowspan: str | None = None,
        scope: str | None = None,
        align: str | None = None,
        axis: str | None = None,
        bgcolor: str | None = None,
        char: str | None = None,
        charoff: str | None = None,
        height: str | None = None,
        valign: str | None = None,
        width: str | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            abbr=abbr,
            colspan=colspan,
            headers=headers,
            rowspan=rowspan,
            scope=scope,
            align=align,
            axis=axis,
            bgcolor=bgcolor,
            char=char,
            charoff=charoff,
            height=height,
            valign=valign,
            width=width,
            **attr,
        )


class thead(Element):
    name = "thead"
    def __init__(
        self,
        styles: css | None = None,
        align: str | None = None,
        bgcolor: str | None = None,
        char: str | None = None,
        charoff: str | None = None,
        valign: str | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            align=align,
            bgcolor=bgcolor,
            char=char,
            charoff=charoff,
            valign=valign,
            **attr,
        )


class time(Element):
    name = "time"
    def __init__(
        self,
        styles: css | None = None,
        datetime: str | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            datetime=datetime,
            **attr,
        )


class title(Element):
    name = "title"
    def __init__(
        self,
        styles: css | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            **attr,
        )


class tr(Element):
    name = "tr"
    def __init__(
        self,
        styles: css | None = None,
        align: str | None = None,
        bgcolor: str | None = None,
        char: str | None = None,
        charoff: str | None = None,
        valign: str | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            align=align,
            bgcolor=bgcolor,
            char=char,
            charoff=charoff,
            valign=valign,
            **attr,
        )


class track(Element):
    name = "track"
    def __init__(
        self,
        styles: css | None = None,
        default: str | None = None,
        kind: str | None = None,
        label: str | None = None,
        src: str | None = None,
        srclang: str | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            default=default,
            kind=kind,
            label=label,
            src=src,
            srclang=srclang,
            **attr,
        )


class tt(Element):
    name = "tt"
    def __init__(
        self,
        styles: css | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            **attr,
        )


class u(Element):
    name = "u"
    def __init__(
        self,
        styles: css | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            **attr,
        )


class ul(Element):
    name = "ul"
    def __init__(
        self,
        styles: css | None = None,
        compact: str | None = None,
        type: str | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            compact=compact,
            type=type,
            **attr,
        )


class var(Element):
    name = "var"
    def __init__(
        self,
        styles: css | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            **attr,
        )


class video(Element):
    name = "video"
    def __init__(
        self,
        styles: css | None = None,
        autoplay: str | None = None,
        controls: str | None = None,
        controlslist: str | None = None,
        crossorigin: str | None = None,
        disablepictureinpicture: str | None = None,
        disableremoteplayback: str | None = None,
        height: str | None = None,
        loop: str | None = None,
        muted: str | None = None,
        playsinline: str | None = None,
        poster: str | None = None,
        preload: str | None = None,
        src: str | None = None,
        width: str | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            autoplay=autoplay,
            controls=controls,
            controlslist=controlslist,
            crossorigin=crossorigin,
            disablepictureinpicture=disablepictureinpicture,
            disableremoteplayback=disableremoteplayback,
            height=height,
            loop=loop,
            muted=muted,
            playsinline=playsinline,
            poster=poster,
            preload=preload,
            src=src,
            width=width,
            **attr,
        )


class wbr(Element):
    name = "wbr"
    def __init__(
        self,
        styles: css | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            **attr,
        )


class xmp(Element):
    name = "xmp"
    def __init__(
        self,
        styles: css | None = None,
        **attr: str
    ) -> None:
        super().__init__(
            styles=styles,
            **attr,
        )

